title: hello-world
description: >-
  I would really really like to learn how to configure gpg to be able to work
  correctly on my old 2011 MacBook pro...or at least have someone else tell me
  how to do so... that would just be so terrific! 
template:
  repo: hello-world-template
  name: hello-world
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
